### ISSUE TITLE
Solution document

### ISSUE THREAD

**Issue by waynemorphic** [waynemorphic/be-dragonfly-barbershop#3]
## Tasks

- [ ] Document the software to map out the dev lifecycle
- [ ] UML diagram to map database
- [ ] Add diagrams to show user journey
